### ISSUE TITLE
Hardcoded rack and board id. Should be in a config file at least.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-snmp-plugin#5]
Is there a common way in the SDK for plugins to pass out board ids?
Problem is here: https://github.com/vapor-ware/synse-snmp-plugin/blob/4dab466d4c95cd5cde673bab2bb992fc9a32947f/snmp/servers/pxgms_ups.go#L87

**Comment by edaniszewski** [comment]
we have similar problems in the IPMI  plugin w.r.t. hardcoded rack/board info.

this is ultimately the same issue that we have come across multiple times in the past year and started to discuss but never reached a conclusion. the tl;dr is that this problem exists because we still use 'rack' and 'board' for routing. this made sense back in the day when it was introduced but doesn't anymore, and we should really have a more generalized approach (e.g. like allowing arbitrary device tags)

see also:
- https://docs.google.com/document/d/1CeIoYsEP2iVKno7ffI5GvCfJhzgxb62TDu9rYL3LdXc/edit#heading=h.e5g452oc3bre
- https://docs.google.com/document/d/1EcIG2kKyDrsClQkg7gGubIABfJLSlKmL7JNTUAC1JWU/edit

**Comment by MatthewHink** [comment]
This is fixed with the SDK 1.0 changes.
